version: "3"

services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - ./src:/app
      - nodemodules:/app/node_modules
      - next:/app/.next
volumes:
  nodemodules:
  next:
